---
# Install required APT packages

- name: Install essential packages for Neovim and LazyVim
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true
  become: true

- name: Create symlink for fd (Ubuntu/Debian compatibility)
  file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  become: true
  when: ansible_os_family == "Debian"
  ignore_errors: true
