---
# Install Rust using rustup

- name: Check if Rust is already installed
  ansible.builtin.command: rustc --version
  register: rust_check
  failed_when: false
  changed_when: false

- name: Install Rust for each target user
  ansible.builtin.include_tasks: rust_user.yml
  loop: "{{ neovim_users }}"
  loop_control:
    loop_var: target_user
