---
# Install Rust using rustup for a specific user

- name: Set user home directory
  ansible.builtin.set_fact:
    user_home: "{{ '/Users/' + target_user if ansible_os_family == 'Darwin' else '/home/' + target_user if target_user != 'root' else '/root' }}"

- name: Check if Rust is already installed for {{ target_user }}
  ansible.builtin.command: rustc --version
  register: rust_check
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ target_user }}"
  environment:
    HOME: "{{ user_home }}"
    PATH: "{{ user_home }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Download rustup installer for {{ target_user }}
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init-{{ target_user }}.sh
    mode: "0755"
  when: rust_check.rc != 0

- name: Install Rust via rustup for {{ target_user }}
  ansible.builtin.shell: /tmp/rustup-init-{{ target_user }}.sh -y --default-toolchain stable
  args:
    creates: "{{ user_home }}/.cargo/bin/rustc"
  become: true
  become_user: "{{ target_user }}"
  environment:
    HOME: "{{ user_home }}"
  when: rust_check.rc != 0

- name: Add Cargo to PATH in bashrc for {{ target_user }}
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: true
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0660"
  become: true
  when: rust_check.rc != 0

- name: Add Cargo to PATH in zshrc for {{ target_user }}
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zshrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: true
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0660"
  become: true
  when: rust_check.rc != 0
  ignore_errors: true

- name: Clean up rustup installer for {{ target_user }}
  ansible.builtin.file:
    path: /tmp/rustup-init-{{ target_user }}.sh
    state: absent
  when: rust_check.rc != 0
