---
# Install tree-sitter CLI for a specific user

- name: Set user home directory
  ansible.builtin.set_fact:
    user_home: "{{ '/Users/' + target_user if ansible_os_family == 'Darwin' else '/home/' + target_user if target_user != 'root' else '/root' }}"

- name: Check if tree-sitter is already installed for {{ target_user }}
  ansible.builtin.command: tree-sitter --version
  register: tree_sitter_check
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ target_user }}"
  environment:
    PATH: "{{ user_home }}/.cargo/bin:{{ ansible_env.PATH }}"
    HOME: "{{ user_home }}"

- name: Install tree-sitter CLI via cargo for {{ target_user }}
  ansible.builtin.command: cargo install tree-sitter-cli
  register: cargo_install_result
  changed_when: "'Installing' in cargo_install_result.stderr or 'Compiling' in cargo_install_result.stderr"
  environment:
    PATH: "{{ user_home }}/.cargo/bin:{{ ansible_env.PATH }}"
    HOME: "{{ user_home }}"
  become: true
  become_user: "{{ target_user }}"
  when: tree_sitter_check.rc != 0
  async: 600
  poll: 10

- name: Verify tree-sitter installation for {{ target_user }}
  ansible.builtin.command: tree-sitter --version
  register: tree_sitter_verify
  changed_when: false
  become: true
  become_user: "{{ target_user }}"
  environment:
    PATH: "{{ user_home }}/.cargo/bin:{{ ansible_env.PATH }}"
    HOME: "{{ user_home }}"
